### ISSUE TITLE
This work on .net6 

### ISSUE THREAD

**Issue by domizacz** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#53] opened 2022-02-17 22:00 UTC
This work on .net 6

**Comment by enzo-ae** [comment] 2022-04-22 09:33
Works for me

**Comment by d-barker** [comment] 2022-08-18 17:08
I have created a PR that updates the packages and targets .net6

I am getting an error where a project that is targeting net6 but uses a standard library that also uses this library is throwing an error with a netcoreapp3.1 reference in the nuget path...
``` shell
Testhost process exited with error: Error:
  An assembly specified in the application dependencies manifest (Diana.Messaging.Tests.deps.json) was not found:
    package: 'AspNetCore.Identity.MongoDbCore', version: '3.1.2'
    path: 'lib/netcoreapp3.1/AspNetCore.Identity.MongoDbCore.dll'
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

**Comment by d-barker** [comment] 2022-08-19 09:33
OK found my issue, was an interesting journey, the cause of above, was due to the fact I was missing this:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk">
        <Version>17.3.0</Version>
    </PackageReference>
```
*sigh*

**Comment by d-barker** [comment] 2023-04-07 04:40
Yes works on .net 6, @alexandre-spieser  you can close this issue.

**Closed** 2023-06-06 15:31 UTC
