### ISSUE TITLE
SignInManager.IsSignedIn method is always false.

### ISSUE THREAD

**Issue by mec2005** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#8] opened 2018-11-03 19:10 UTC
Hi Alexandre, I wanted to congratulate you because it is a nice job.

I got your code and goes run, its compilies correctely, created the base on mongo and registered a user, but after the login its behavior is like I never did the login before.

Could you help me with that, nothing was modified in your code.

![image](https://user-images.githubusercontent.com/2211448/47956383-5e8f6b00-df82-11e8-9b92-19f1a6ba0b5e.png)

**Comment by alexandre-spieser** [comment] 2018-11-07 15:03
Hi, sorry I was on holiday with limited internet access.
It seems like your User identity is not Authenticated and no username, so the behavior seems correct: the user is not signed in.
Have you setup authentication correctly?

**Comment by mec2005** [comment] 2018-11-07 16:56
Hi Alexandre.
No problem, I'm not in a hurry.
About the problem, I got your job, installed mongo and run your code.

I could register a User, I can see it on mongo. 
In login page I put the user information and on server I receive the correctly the data and SignIn was 
successfully.
```
// LOGIN
var result = await _signInManager.PasswordSignInAsync(
                               model.Email, model.Password, 
                               model.RememberMe, 
                               lockoutOnFailure: false);
                if (result.Succeeded)// Here was true, login is successfully
                {
                    _logger.LogInformation(1, "User logged in.");
                    return RedirectToLocal(returnUrl);
                }
```
But here , when the page was redirected to home the method IsSignedIn() always returns false.
```
// _LoginPartial
@if (SignInManager.IsSignedIn(User))
{}
```
I changed nothing on your job, I was just testing to understand it.
I Hope I could explain my problem.

Regards.

**Comment by alexandre-spieser** [comment] 2018-11-07 17:18
oki, I'll have a look this evening :)

**Comment by alexandre-spieser** [comment] 2018-11-07 22:12
I don't know what your setup is, but it works for me.
I started the sample MVC application [here ](https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/master/sample/MongoIdentitySample.Mvc.)and registered. After login I was marked as signed in.

![image](https://user-images.githubusercontent.com/12091458/48164271-ee624b80-e2d9-11e8-9a54-60cbe375d113.png)

**Comment by mec2005** [comment] 2018-11-08 01:13
My brother, I still appreciate your job.
I downloaded it again and started testing.

I noticed that you applied a test into HomeController, because it doesn't have the lines above. No problem.

![image](https://user-images.githubusercontent.com/2211448/48170456-bf9aa400-e2de-11e8-8fd2-8c3654cbb53d.png)

Then I did the login,  it works well but I think it is not setting into User (Principal)
![image](https://user-images.githubusercontent.com/2211448/48170867-92e78c00-e2e0-11e8-831d-876227881f49.png)

I did the same as yours to test SingIn, but I still getting false :(
![image](https://user-images.githubusercontent.com/2211448/48169940-8a8d5200-e2dc-11e8-9f56-48c15a51817e.png)

My Mongo Compass. Account Register is working well!
![image](https://user-images.githubusercontent.com/2211448/48170785-1f457f00-e2e0-11e8-9a26-7dd2af9fe14c.png)

It looks crazy, you have no issue and it has a lot of people using without problem.
I hope you help me.

Best regards.

**Comment by alexandre-spieser** [comment] 2018-11-08 12:47
Seems like you might have a cookie issue. Can you verify that the cookie is returned and sent correctly?

**Comment by mec2005** [comment] 2018-11-08 12:53
Of course I can, but only in the evening.
Do you have any tip that I can see it easily?

Tks

Em qui, 8 de nov de 2018 09:47, Alexandre SPIESER <notifications@github.com
escreveu:

**Comment by alexandre-spieser** [comment] 2018-11-08 14:49
You can inspect the HttpContext to look for the cookies while debugging and look for cookies using Chrome.

**Comment by xclud** [comment] 2018-11-08 15:32
I am facing a similar issue today. to me `SignInManager.PasswordSignInAsync` always returns `Failed`. It was working yesterday but today it is not working and i have not changed a single line of code.

**Comment by alexandre-spieser** [comment] 2018-11-08 17:17
@xclud your issue seems different, because @mec2005 does not have a Failed result on PasswordSignInAsync, it succeeds but the user is not signed In.

**Comment by xclud** [comment] 2018-11-08 20:01
I figured out calling `SignInManager.IsSignedIn(User)` will break your login logic and makes session and cookies empty, and it makes the app seem it never logged in.

@mec2005 A work around to this bug is:
```
var user = await UserManager.GetUserAsync(User);
if (user != null)
{
    //Your logic.
}
```

**Comment by alexandre-spieser** [comment] 2018-11-08 20:50
The behaviour of the `SignInManager.IsSignedIn(User)` method is as follows (https://github.com/aspnet/Identity/blob/master/src/Identity/SignInManager.cs).
```
        /// <summary>
        /// Returns true if the principal has an identity with the application cookie identity
        /// </summary>
        /// <param name="principal">The <see cref="ClaimsPrincipal"/> instance.</param>
        /// <returns>True if the user is logged in with identity.</returns>
        public virtual bool IsSignedIn(ClaimsPrincipal principal)
        {
            if (principal == null)
            {
                throw new ArgumentNullException(nameof(principal));
            }
            return principal?.Identities != null &&
                principal.Identities.Any(i => i.AuthenticationType == IdentityConstants.ApplicationScheme);
        }
```
 I do not think it impacts any session.

**Comment by xclud** [comment] 2018-11-08 20:53
You're right. I try to figure out why calling it breaks everything.

**Comment by mec2005** [comment] 2018-11-09 01:48
Hi Alexandre.
I took look at the cookie after the login and it was I could see.
![image](https://user-images.githubusercontent.com/2211448/48234137-75c5c280-e39f-11e8-9b33-2f26f40188f4.png)

I Noticed that it could be a problem, there was nothing about  user in session or cookie.

To not to leave doubts, I changed 
`app.UseIdentity();`
to
`app.UseAuthentication();`            
![image](https://user-images.githubusercontent.com/2211448/48235094-a7d92380-e3a3-11e8-9ad5-8087267b5e66.png)

And I add `services.AddAuthentication` on Startup
![image](https://user-images.githubusercontent.com/2211448/48236941-93992480-e3ab-11e8-85ce-666c63fefef2.png)

-----------------------------

:-( Without success it still not working.

And then I decided to create the Identity Principal manually.
Its is not what I wanted.
I changed 
`_signInManager.SignInAsync`
to
`HttpContext.SignInAsync` 

Into Account.Login
![image](https://user-images.githubusercontent.com/2211448/48236765-db6b7c00-e3aa-11e8-9187-4d995b6a14a8.png)

To finally I modify the Home.Index, I add IsSignedIn just to test `AuthenticationType == "cookie"`
![image](https://user-images.githubusercontent.com/2211448/48237430-b3c9e300-e3ad-11e8-8992-333ceafa8d84.png)

Debugging I got `IsAuthenticated == true` with my data and claims.
![image](https://user-images.githubusercontent.com/2211448/48237650-b5e07180-e3ae-11e8-933b-f74b22568a79.png)

Alexandre, now it is in cookie, but I really didn't want to change nothing in your job, I'm not sure about doing this. I appreciate to understand how your code works and mimes not, maybe there are diferences between codes.

I hope I could explain my problem!
Regards.

**Comment by alexandre-spieser** [comment] 2018-11-09 10:31
Yeah that's very weird, you do not have cookies, the startup.cs here https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/sample/MongoIdentitySample.Mvc/Startup.cs
should make it work without issues. 
Is your environment variable correctly setup? The `.AddDefaultTokenProviders()` should take care of setting up cookies. Do you have any cookie blocker on your browser?

**Comment by xclud** [comment] 2018-11-09 10:42
It turned out to me the behavior is completely random on my side. Either `SignInAsync` and `PasswordSignInAsync` work or nothing works. It works now and doesn't work next hour.

Sometimes it works and when i deploy a new build to the IIS it stops working. And again with the next deployment it works. Sometimes the only change i make is just related to CSS but it breaks and fixed from deployment to deployment. Quite weird.

I am going to add the source code to the VS solution to go for a deep debug. I will let you know what happens.

**Comment by mec2005** [comment] 2018-11-09 10:59
Alexandre, an unusual think is that I use a hyper-v, I noticed that cookie
is working but not as we expected, like You said maybe something into
AddDefaultTokenProviders()
:(
I know nothing more I can do.

I'll try some changes that I didn't want, but the important is it works
well.

Thank you very much.

Em sex, 9 de nov de 2018 07:31, Alexandre SPIESER <notifications@github.com
escreveu:

**Comment by alexandre-spieser** [comment] 2018-11-09 11:32
@xclud maybe look at the Identity source of the managers to see what's up.
I have a snapshot of the Identity source I took a few months ago:
https://github.com/alexandre-spieser/Identity/blob/dev/src/Identity/SignInManager.cs
It is also important to notice in `AspNetCore.Identity.MongoDbCore` I do not change any of the managers implementation. The package only contains implementation for the UserStores and RoleStores to run on top of MongoDB, along with Identity 2.0.1. 
If the SignInManager has a bug in it and it is not fixed by the Microsoft team, then I can not do much. 
I can only fix bugs in the MongoDB stores and my other package, `MongoDbGenericRepository`.
The dependencies of this package (current version is 1.0.9) are:

+ Microsoft.AspNetCore.Identity" version="2.0.1"
+ Microsoft.Extensions.Identity.Stores" version="2.0.1"
+ MongoDB.Driver" version="2.7.0"
+ MongoDbGenericRepository" version="1.3.8"

I am planning to upgrade the Identity packages to a new version soon however.

**Comment by alexandre-spieser** [comment] 2018-11-18 13:51
New package published, it has the latest update to identity.

**Comment by xclud** [comment] 2018-11-18 18:58
I updated the package and it turned out the problem is not with this library.

I am almost satisfied this is a bug in MongoDB driver for C#. It sometimes looks for documents with camelCase property names and sometimes for PascalCase names. I had to enforce my casing convention in Startup class constructor and it turned out it works perfectly in mongodb library version 2.7 and 2.7.2. But still buggy in 2.7.1.

Either version 2.7. or 2.7.2 i use, I have to enforce my casing convention. I am completely sure this is not a conflict/race condition with casing of mongodb. All nuget libraries i use are independent form mongodb. So they may not change the behavior.

On your side @alexandre-spieser, It almost read the source code of AspNetCore.Identity.MongoDbCore and found nothing. I suspect if one of your dependencies try to change the default behavior?! Unfortunately i didn't get to check the dependencies of AspNetCore.Identity.MongoDbCore.

Maybe we can take this as a hint to finally find the bug?

**Comment by alexandre-spieser** [comment] 2018-11-18 19:42
By default the collectioname is the name of the type of your model, and it is camelcased.
AspNetCore.Identity.MongoDbCore relies on my other MongoDbGenericRepository package for data access.
However I do not change the convention on the naming of the property names.
This is what my default applicationUsers collections looks like:
![image](https://user-images.githubusercontent.com/12091458/48677259-fa67cc00-eb69-11e8-964f-d9b510871c38.png)

**Closed** 2018-12-01 09:12 UTC

**Comment by dlopatin-ms** [comment] 2019-04-12 12:14
I'm using Identity server 4 with IdentityFramework. I have the same problems: User.Identity.IsAuthenticated = false after success login.
The issue happens that does not appear. Also the problem depends on the browser: for now it doesn't work in Chrome and Opera but works in Edge. 
For db I use MySql(Pomelo). 
I tried everything from this topic, but nothing works for me.

**Comment by dlopatin-ms** [comment] 2019-04-12 12:48
I think I found the cause of this problem. The problem disappears when I use HTTPS. For me, this solution is enough, but it's still interesting to know how it can be configured in the code. I will be glad to any advice.

**Comment by alexandre-spieser** [comment] 2019-04-12 15:26
```
For db I use MySql(Pomelo).
```
This repo is a MongoDb UserStore and RoleStore adapter for Microsoft.AspNetCore.Identity 2.0. Allows you to use MongoDb instead of SQL server with Microsoft.AspNetCore.Identity 2.0.
It seems like you're having a problem with Identity, not the MongoDB store.

**Comment by dlopatin-ms** [comment] 2019-04-12 15:32
> ```
> For db I use MySql(Pomelo).
> ```
> This repo is a MongoDb UserStore and RoleStore adapter for Microsoft.AspNetCore.Identity 2.0. Allows you to use MongoDb instead of SQL server with Microsoft.AspNetCore.Identity 2.0.
> It seems like you're having a problem with Identity, not the MongoDB store.

I know, just the problem the same. :)

**Comment by zandiarash** [comment] 2020-02-08 19:02
> Seems like you might have a cookie issue. Can you verify that the cookie is returned and sent correctly at each request? The domain for your cookie or your browser settings might be different than mine.

I cleared cookies and my problem was solved, thanks

**Comment by BiradarMallikarjun** [comment] 2020-07-18 17:23
I have same issue!

Fix:  in Startup.cs file under Configure() method, 

           Added this line -  **_app.UseAuthentication();_** 

before: 

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });

**Comment by 2Xpro-pop** [comment] 2022-06-10 13:38
> > Seems like you might have a cookie issue. Can you verify that the cookie is returned and sent correctly at each request? The domain for your cookie or your browser settings might be different than mine.
> 
> I cleared cookies and my problem was solved, thanks

Thank you my friend! I am very grateful to you.
